services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"

networks:
  frontend:
    # Specify driver options
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"