services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"